// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuj7iTixgkR01DMbyD4BMouzdz50AP16Q',
    appId: '1:890417640755:web:688c6e0298dcd312a77a46',
    messagingSenderId: '890417640755',
    projectId: 'upangeats',
    authDomain: 'upangeats.firebaseapp.com',
    storageBucket: 'upangeats.appspot.com',
    measurementId: 'G-SBC6055ZTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDPuDoSdlZF0cm2Qaa5o2nH00toYHNFFo',
    appId: '1:890417640755:android:7692fcf830d7105ba77a46',
    messagingSenderId: '890417640755',
    projectId: 'upangeats',
    storageBucket: 'upangeats.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8_K24RxC-b3lq17Pe0JCo-6aFgXdzztM',
    appId: '1:890417640755:ios:d80276ffa0256aefa77a46',
    messagingSenderId: '890417640755',
    projectId: 'upangeats',
    storageBucket: 'upangeats.appspot.com',
    iosBundleId: 'com.example.upangeatt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8_K24RxC-b3lq17Pe0JCo-6aFgXdzztM',
    appId: '1:890417640755:ios:06a007f1075fe310a77a46',
    messagingSenderId: '890417640755',
    projectId: 'upangeats',
    storageBucket: 'upangeats.appspot.com',
    iosBundleId: 'com.example.upangEat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuj7iTixgkR01DMbyD4BMouzdz50AP16Q',
    appId: '1:890417640755:web:c6f81702e6581988a77a46',
    messagingSenderId: '890417640755',
    projectId: 'upangeats',
    authDomain: 'upangeats.firebaseapp.com',
    storageBucket: 'upangeats.appspot.com',
    measurementId: 'G-S1T8NXC8F6',
  );
}
